### ISSUE TITLE
When incident count is empty, show a link for users to report incidents

### ISSUE THREAD

**Issue by lima01** [lima01/hatecrimetracker-frontend#15]
When user select a location and date range where there is no data collected, instead of showing an empty chart, we can put an overlay on top of the empty chart, and say:
"There is no data collected in the selected location and date range yet. Click _here_ to let us report incidents."

Here will link to a Google form.

**Comment by 1ThingAgainstRacism** [comment]
The form has been created: https://forms.gle/HRkVKW2Sfp7BytXj8
